import paimonIds from '../data/paimonIds.json' with {type:'json'};
import {findCharacter,findWeapon} from './assets.js';
export const BANNERS={'301':'Character Event','400':'Character Event','302':'Weapon Event','200':'Standard','500':'Chronicled','100':'Beginner'};
const normalizeBanner=x=>String(x||'200');
export function normalizeWish(x,source='JSON import',banner){if(!x||typeof x!=='object')return null;let rawId=String(x.id??x.wish_id??'');let itemName=String(x.name??x.itemName??'').trim();let itemId=String(x.item_id??x.itemId??'');let bannerType=normalizeBanner(x.gacha_type??x.bannerType??banner);let date=String(x.time??x.date??'').trim();if(!date||!itemName&&!itemId)return null;
let item=findCharacter(itemName)||findWeapon(itemName);let rarity=Number(x.rank_type??x.rarity??item?.rarity)||null;if(![3,4,5].includes(rarity))rarity=null;
return {id:rawId||`manual-${bannerType}-${date}-${itemName}-${itemId}`,date,itemName:itemName||`Unresolved item · ${itemId}`,itemId:itemId||item?.id||'',rarity,bannerType,source,itemType:x.item_type||x.itemType||null,uid:x.uid?String(x.uid):null,pityAtPull:Number(x.pityAtPull??x.pity)||null};}
export function parseWishJSON(raw){let obj=typeof raw==='string'?JSON.parse(raw):raw;let result=[];let push=(rows,source,banner,uid)=>{if(Array.isArray(rows))result.push(...rows.map(x=>normalizeWish(uid?{...x,uid:x.uid??uid}:x,source,banner)).filter(Boolean))};
if(Array.isArray(obj))push(obj,'JSON import');
if(Array.isArray(obj?.data?.list))push(obj.data.list,'HoYoverse JSON');
if(Array.isArray(obj?.hkrpg))throw Error('This file contains Star Rail wishes, not Genshin wishes.');
if(Array.isArray(obj?.list))push(obj.list,'UIGF JSON');
if(Array.isArray(obj?.uigf_gacha_log?.list))push(obj.uigf_gacha_log.list,'UIGF JSON');
if(Array.isArray(obj?.genshin)){for(const account of obj.genshin)push(account.list||account.records,'UIGF JSON',null,account.uid);}
if(Array.isArray(obj?.records))push(obj.records,'JSON import');
// Paimon.moe local backup: account-prefixed wish-counter-* keys contain {pulls:[{id,time,type,pity}]}.
for(const [key,value] of Object.entries(obj||{})){let match=key.match(/wish-counter-(character-event|weapon-event|standard|beginners|chronicled)/);if(!match)continue;let banner=({'character-event':'301','weapon-event':'302',standard:'200',beginners:'100',chronicled:'500'})[match[1]];let data=typeof value==='string'?JSON.parse(value):value;const rows=data?.pulls;if(!Array.isArray(rows))continue;for(let i=0;i<rows.length;i++){let row=rows[i];const backupUid=key.match(/^(\d{9,10})-wish-counter-/)?.[1]||null;let mapped=paimonIds[String(row.id)]||null;let item=findCharacter(mapped?.name||row.id)||findWeapon(mapped?.name||row.id);
const name=row.name||mapped?.name||item?.name||'';let time=typeof row.time==='number'?new Date(row.time<1e12?row.time*1000:row.time).toISOString():row.time;const parsed=normalizeWish({...row,id:`paimon-${banner}-${time}-${row.id}-${i}`,itemName:name,itemId:row.id,date:time,uid:row.uid||backupUid,rarity:row.rarity||item?.rarity,bannerType:banner},'Paimon.moe backup',banner);if(parsed)result.push(parsed)}}
if(!result.length)throw Error('No supported Genshin wish records found. Try a UIGF JSON export or a Paimon.moe Settings backup.');return result;}
export function mergeWishes(previous,incoming){const map=new Map();const put=(records)=>{const seen=new Map();for(const row of records){if(!row?.date)continue;const canonical=findCharacter(row.itemName)||findWeapon(row.itemName);const base=`${row.bannerType}:${row.date}:${canonical?.id||row.itemId||row.itemName.toLowerCase()}`;const ordinal=seen.get(base)||0;seen.set(base,ordinal+1);const key=`${base}:${ordinal}`;const old=map.get(key);if(!old||row.source==='HoYoverse history')map.set(key,row)}};put(previous);put(incoming);return [...map.values()].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));}
export function calculateWishStats(all,type){const rows=all.filter(x=>!type||type==='all'||(type==='301'?(x.bannerType==='301'||x.bannerType==='400'):x.bannerType===type));let since5=0,since4=0,five=[],four=[],last5=null,last4=null;for(const x of rows){since5++;since4++;if(x.rarity===5){five.push({...x,pityAtPull:x.pityAtPull||since5,completePity:!!last5});last5=x;since5=0;since4=0;last4=x}else if(x.rarity===4){four.push({...x,pityAtPull:since4,completePity:!!last4});last4=x;since4=0}}const complete=five.filter(x=>x.completePity);return {total:rows.length,five,four,pity:since5,pity4:since4,average:complete.length?Math.round(complete.reduce((a,x)=>a+x.pityAtPull,0)/complete.length):null,highest:complete.length?Math.max(...complete.map(x=>x.pityAtPull)):null,complete:false};}
export function planWishes({primogems=0,fates=0,pity=0,guaranteed=false,constellations=0}){const available=Math.floor(Math.max(0,+primogems||0)/160)+Math.max(0,+fates||0);const copies=Math.max(1,(+constellations||0)+1);const worst=(guaranteed?90:180)-Math.min(89,Math.max(0,+pity||0))+Math.max(0,copies-1)*180;return {available,worst,shortfall:Math.max(0,worst-available),primogemsNeeded:Math.max(0,worst-available)*160};}
