"""Source-transcribed non-KQM guides for characters without a KQM build guide.
Only same-source explicitly named build items are included. The Manekin guide applies the
same generalist advice to both models / elements; it makes no element-specific team claims.
"""
import json
from pathlib import Path
root=Path('src/data');cat=json.loads((root/'catalog.json').read_text());meta=json.loads((root/'entityMeta.json').read_text());chars={x['id']:x for x in cat['characters']};weapons={x['name']:x for x in cat['weapons']};artifacts={x['name']:x for x in cat['artifacts']};today='2026-09-27';out={}

def weapon(name,category,context,guide,build):
 w=weapons[name];m=meta['weapons'].get(name,{});return dict(id=w['id'],name=name,category=category,isBiS=category=='BiS',isSignature=False,context=context,note=context,baseAtk90=m.get('baseAtk90'),secondary=w.get('secondary'),secondaryValue90=m.get('secondaryValue90'),refinement='R1 baseline; consult item for R2–R5',source=guide['source'],sourceUrl=guide['sourceUrl'],version=guide['version'],lastUpdated=guide['lastUpdated'],lastReviewed=today,buildId=build)
def artifact(name,category,context,guide,build):
 a=artifacts[name];return dict(id=a['id'],name=name,category=category,pieceCount=4,context=context,source=guide['source'],sourceUrl=guide['sourceUrl'],version=guide['version'],lastUpdated=guide['lastUpdated'],lastReviewed=today,buildId=build)
def talents(order,guide,build,reason,automatic=False):
 records=[]
 for tid in ['normal','skill','burst']:
  known=tid in order
  records.append(dict(talentId=tid,priority=('AUTOMATIC' if automatic else 'PRIMARY' if known and order.index(tid)==0 else 'SECONDARY' if known else None),recommendedLevel=None,levelSpecified=False,levelSource=None,source=guide['source'],sourceUrl=guide['sourceUrl'] if known else None,version=guide['version'],lastUpdated=guide['lastUpdated'],lastReviewed=today,buildId=build,reason=reason if known else 'DATA NOT VERIFIED · the cited build summary does not set a per-talent priority.'))
 return records

def guide(cid,source,url,version,updated,summary,name,weaponRows,artifactRows,stats,substats,priority,talentNote,notes,teamStatus,materialStatus):
 c=chars[cid];build='alt-'+cid;g=dict(characterId=cid,source=source,sourceUrl=url,version=version,sourceVersion=version,lastUpdated=updated,lastReviewed=None,reviewedAt=None,sourceIndexedAt=today,guideStatus='source_structured',status='REVIEW NEEDED',freshnessStatus='REVIEW NEEDED',reviewMethod='Structured source excerpt; no unsupported numerical talent targets or team roles inferred.',summary=summary,playstyles=[{'role':name,'overview':summary}],sourceRosters=[],teamDataStatus=teamStatus,farmingSource=materialStatus,variants=[])
 v=dict(id=build,name=name,context='Source-specified; select for this playstyle',description=summary,weapons=[weapon(n,k,t,g,build) for n,k,t in weaponRows],artifacts=[artifact(n,k,t,g,build) for n,k,t in artifactRows],mainStats=stats,substats=substats,statNotes=notes,talents=talents(priority,g,build,talentNote,automatic=(source=='Icy Veins')),teams=[])
 g['variants']=[v];return g

g8='Game8 · Genshin Impact build guide'
icy='Icy Veins · Manekin & Manekina Guide and Overview'
icyurl='https://www.icy-veins.com/genshin-impact/manekin-guide-and-overview'
for cid,c in chars.items():
 if c['name'] not in ('Manekin','Manekina'):continue
 out[cid]=guide(cid,icy,icyurl,'Not stated','2025-10-18','Open-world elemental driver; the current element follows the Traveler. Icy Veins recommends a flexible ATK/CRIT generalist setup rather than element-locked gear. Not usable in endgame modes.','On-field elemental generalist', [('The Black Sword','SOURCE LISTED','4-star CRIT stat stick in the source guide'),('Blackcliff Longsword','SOURCE LISTED','CRIT stat stick in the source guide'),('Wolf-Fang','SOURCE LISTED','CRIT stat stick in the source guide')],[("Gladiator's Finale",'RECOMMENDED','Source recommends a flexible generalist set for open-world on-field attacks.')],{'sands':'ATK%','goblet':'ATK%','circlet':'CRIT Rate / CRIT DMG'},'ER to Burst requirement, then CRIT and ATK%. Element-specific builds are not assessed by this generalist source.',['normal','skill','burst'],'Talents automatically level with the character; do not farm separate talent books.',['No character leveling materials or separate talent leveling: progress in Miliastra Wonderland levels the Manekin automatically.','Only one Manekin or Manekina may be in the party, and the character is not playable in endgame modes.'],'DATA NOT VERIFIED · the source does not give an exact four-member party for this elemental mode.','No material farming; source says upgrades follow Miliastra Wonderland progress.')

# Current Game8 source pages have explicit item choices. Team roles and rotations are not
# inferred from their example thumbnails; see each source for the complete discussion.
out['10000143']=guide('10000143',g8,'https://game8.co/games/Genshin-Impact/archives/606901','7.1','2026-09-25','On-field Stellar-Swirl DPS. Game8 recommends ATK% and CRIT with a Stellar-Swirl artifact set; an Anemo DMG Goblet is not its recommended main stat.','Stellar-Swirl on-field DPS',[('Beyond the Chrysalis','BiS','Source lists as best weapon and identifies it as Vesna’s tailored option.'),('Whitelake Frostfeather','ALTERNATIVE','Source lists among alternative swords.'),('Azurelight','ALTERNATIVE','Source lists among alternative swords.')],[('Scarlet Proof','PRIMARY','Source best set for Stellar-Swirl damage and ATK. Context: on-field Stellar-Swirl DPS.'),('Viridescent Venerer','ALTERNATIVE','Source alternative where the team lacks RES Shred.')],{'sands':'ATK%','goblet':'ATK%','circlet':'CRIT Rate / CRIT DMG'},'CRIT and ATK%; ER until team-specific requirement. Game8 warns against assuming an Anemo DMG Goblet for this playstyle.',[],'DATA NOT VERIFIED · this page extract does not establish individual numeric talent targets.',['Game8 cites teams with Cryo Traveler, Odette and C6 Faruzan; its example roles/rotations have not been independently transcribed.'],'Source examples exist; four-member roles and rotations require separate verification.','DATA NOT VERIFIED · no exact farming source mapped for this character.')
out['10000140']=guide('10000140',g8,'https://game8.co/games/Genshin-Impact/archives/606400','7.1','2026-09-25','HP-scaling Hydro support and healer for Freeze and Stellar-Swirl. Game8 recommends building HP for her buffs and sustain; Burst uptime is optional.','Off-field HP support / healer',[('Hymn of the Maelstrom','SIGNATURE','Source best weapon; evaluate team alternatives separately.'),('Thrilling Tales of Dragon Slayers','ALTERNATIVE','Source alternative for ATK-scaling teammates.'),('Prototype Amber','ALTERNATIVE','Source alternative HP Catalyst.')],[('Tenacity of the Millelith','PRIMARY','Source option for HP and a party ATK buff if no other holder.'),('Song of Days Past','ALTERNATIVE','Source option focused on healing and support.')],{'sands':'HP%','goblet':'HP%','circlet':'HP% (Healing Bonus situational)'},'HP% first, then ER only if using Burst; source discusses a 65,000 HP buff cap in context.',[],'DATA NOT VERIFIED · this page extract does not establish individual numeric talent targets.',['Game8 supplies a Skirk–Escoffier–Furina–Vodyanitsa Freeze roster and a Vesna Stellar-Swirl roster; inspect the original for rotation details.'],'Source examples exist; team roles/rotations not independently validated.','DATA NOT VERIFIED · no exact farming source mapped for this character.')
for cid in ['10000005-505','10000007-705']:
 out[cid]=guide(cid,g8,'https://game8.co/games/Genshin-Impact/archives/613906','7.0','2026-09-10','Cryo Traveler can deal Stellar-Conduct damage or support Stellar-Swirl. Game8 presents distinct artifact sets for these contexts; do not treat them as interchangeable.','Cryo Stellar Glimmer DPS / support',[('Exaiphanes Blade','BiS','Game8 best weapon for its Traveler Stellar Glimmer build.'),('Primordial Jade Cutter','ALTERNATIVE','Source alternative sword.'),('Wolf-Fang','ALTERNATIVE','Source alternative sword.')],[('Disenchantment in Deep Shadow','PRIMARY','Source preference in Stellar-Conduct damage teams.'),('Tenacity of the Millelith','SITUATIONAL','Source preference for Stellar-Swirl support or Sub-DPS.')],{'sands':'ATK%','goblet':'ATK%','circlet':'CRIT Rate / CRIT DMG'},'CRIT then ATK, with ER for team-specific Burst uptime; context differs for Stellar-Conduct and support.',[],'DATA NOT VERIFIED · no individual numeric talent target verified.',['KQM 7.0 version overview independently discusses Exaiphanes Blade and Heart of the Furnace in the Cryo Traveler context; Game8 page provides this build’s gear choices.'],'Source examples exist; on-field role, party assignments and rotations require validation.','DATA NOT VERIFIED · no character-specific farming table mapped.')
# Talent priorities verified independently where the primary source excerpt does not specify them.
# Per-field provenance deliberately differs from primary gear source.
def sourced_priority(cid,order,source,url,updated,reason):
 g=out[cid];v=g['variants'][0];v['talents']=[dict(talentId=tid,priority='PRIMARY' if i==0 else 'SECONDARY' if i==1 else 'LOW',recommendedLevel=None,levelSpecified=False,levelSource=None,source=source,sourceUrl=url,version=g['version'],lastUpdated=updated,lastReviewed=today,buildId=v['id'],reason=reason) for i,tid in enumerate(order)]
sourced_priority('10000143',['skill','burst','normal'],'Eurogamer','https://www.eurogamer.net/genshin-impact-best-vesna-build','2026-09-23','Eurogamer: Skill > Burst; Normal Attack is not the central damage talent. No numeric target specified.')
sourced_priority('10000140',['skill','burst','normal'],'Sportskeeda','https://www.sportskeeda.com/esports/genshin-impact-vodyanitsa-build-guide-best-weapons-artifacts-teams','2026-09-22','Sportskeeda: Skill > Burst > Normal Attack in a support build. No numeric level set.')
for cid in ['10000005-505','10000007-705']:
 sourced_priority(cid,['burst','normal','skill'],'Icy Veins','https://www.icy-veins.com/genshin-impact/cryo-traveler-guide-best-builds','2026-09-09','Icy Veins: Burst first, Normal Attack next for on-field Cryo Traveler; Skill is application and does not need investment for direct Stellar damage. No numeric target specified.')
# Source-listed four-person compositions only. No rotation is invented from the party caption.
charbyname={x['name']:x['id'] for x in cat['characters'] if x['name']!='Traveler'}
def add_team(owner,team_id,names,roles,archetype,source_url,version,updated,context):
 g=out[owner];ids=[charbyname[name] for name in names];assert len(set(ids))==4 and len(names)==len(roles)==4
 g['variants'][0]['teams'].append(dict(id=team_id,mainDps=names[0],mainDpsId=ids[0],members=names,memberIds=ids,roles=roles,archetype=archetype,reaction=archetype,buildContext=context,playstyle=context,rotation='Source does not specify this exact rotation.',rotationContext='Source does not specify this exact rotation.',requirements=['Follow the linked composition; check availability and team mechanics before investing.'],advantages=[context],limitations=['Current-version ranking and exact rotation not independently confirmed.'],notes='Exact quartet from linked source; no slot-swap invented.',source='KeqingMains' if 'keqingmains' in source_url else g8,sourceUrl=source_url,version=version,lastUpdated=updated,lastReviewed=today,buildId=g['variants'][0]['id'],reviewStatus='REVIEW NEEDED · source roster checked; rotation not certified'))
add_team('10000143','vesna-diona-odette-faruzan',['Vesna','Diona','Odette','Faruzan'],['ON-FIELD DPS','CRYO SUPPORT','CRYO SUPPORT','ANEMO SUPPORT'],'Stellar-Swirl','https://keqingmains.com/q/diona-quickguide/','7.1','2026-09-24','KQM Diona guide lists this C6-Diona and C6-Faruzan Vesna composition; Constellations matter.')
add_team('10000140','vody-skirk-escoffier-furina',['Skirk','Escoffier','Furina','Vodyanitsa'],['ON-FIELD DPS','CRYO SUB DPS','HYDRO SUB DPS / SUPPORT','HYDRO HEALER / SUPPORT'],'Freeze','https://game8.co/games/Genshin-Impact/archives/606400','7.1','2026-09-25','Game8 lists Skirk–Escoffier–Furina–Vodyanitsa together; Vodyanitsa heals for Furina.')
(root/'alternateGuides.json').write_text(json.dumps(out,ensure_ascii=False,separators=(',',':'))+'\n');print('Generated',len(out),'source-attributed alternatives;',sum(x['source']==icy for x in out.values()),'Manekin variants')
