// Curated "which constellations matter" notes (original summaries).
// 5★ characters: exactly ONE key con (or none). 4★: all impactful cons.
// { charKey: { best: [consNumbers], note } }

export const consNotes = {
  // ---- 5 stars: single key con ----
  'raiden-shogun': { best: [2], note: 'C1 is a nice Resolve boost, but C2 (60% DEF ignore) is THE famous damage spike — the one worth planning for.' },
  'hu-tao': { best: [1], note: 'C1 (no stamina for charged attacks) massively smooths her whole playstyle and adds real damage. Nothing else comes close in value.' },
  neuvillette: { best: [1], note: 'C1 gives interruption resistance during the beam plus an extra passive stack — the single biggest comfort/damage upgrade he has.' },
  furina: { best: [2], note: 'C2 hugely raises the Fanfare cap — roughly a ~50-60% personal damage jump and one of the most valuable constellations ever released. C1 is only a convenience next to it.' },
  nahida: { best: [2], note: 'C1 is minor; C2 adds Defense shred + crit to the Burning/Bloom family — her key con.' },
  'kamisato-ayaka': { best: [1], note: 'C1 improves energy and rotation flow; her real spike is C6 but C1 is the sensible stop.' },
  'kaedehara-kazuha': { best: [2], note: 'C1 helps rotations; C2 gives +200 EM to himself AND the team — the premium support upgrade.' },
  zhongli: { best: [], note: 'C0 Zhongli already does his job perfectly (shield + shred). Cons are pure luxury.' },
  yelan: { best: [2], note: 'C2 adds real off-field damage — the key con. (C1\'s extra Skill charge is beloved for exploration QoL, but it\'s not the damage pick.)' },
  xianyun: { best: [2], note: 'C1 improves her Skill; C2 adds a strong team ATK buff — her key support con.' },
  arlecchino: { best: [1], note: 'C1 is widely considered one of the best C1s in the game: strong interruption resistance plus a big Blood-Debt damage boost in one node. C2 is a luxury on top.' },
  mavuika: { best: [2], note: 'C1 boosts Fighting Spirit and ATK; C2 is one of the largest C2 damage jumps in the game — the one to plan around.' },
  xilonen: { best: [2], note: 'C1 removes DEF snapshot quirks; C2 adds big off-field buffs — her defining support con.' },
  citlali: { best: [1], note: 'C1 adds strong Frost damage and more shred value — the clear early stop.' },
  mualani: { best: [1], note: 'C1 is a huge Sharky Bite multiplier — the standout con by far.' },
  clorinde: { best: [1], note: 'C1 extra Hunter\'s Vigil hits is her cleanest damage-per-pull upgrade.' },
  navia: { best: [2], note: 'C1 refunds shard charges (QoL); C2 adds crit rate per shard — the key damage con.' },
  skirk: { best: [2], note: 'C1 boosts Seven-Phase Flash chains; C2 extends her damage windows — the bigger jump.' },
  wanderer: { best: [1], note: 'C1 speeds up and strengthens his attacks noticeably; later cons are luxury.' },
  xiao: { best: [1], note: 'C1 extra Skill charge improves rotation comfort; his damage cons come much later.' },
  ganyu: { best: [1], note: 'C1 gives energy and a Cryo RES shred on charged shots — modest but the best early value.' },
  alhaitham: { best: [2], note: 'C1 improves Skill cooldown; C2 grants stacking EM — his best value con.' },
  cyno: { best: [1], note: 'C1 speeds his Burst attacks; big spikes are C2 and beyond but C0 works fine.' },
  eula: { best: [1], note: 'C1 boosts Physical DMG through Grimheart — solid, though her weapon matters more.' },
  lyney: { best: [1], note: 'C1 extra prop and crit — a clean damage boost for his charged-shot loop.' },
  wriothesley: { best: [], note: 'Community testing found his C1 one of the smallest C1 gains of its era — none of his early cons are worth planning around. Take his signature weapon instead.' },
  kinich: { best: [2], note: 'C1 adds Loop Shot damage, but C2 (Dendro RES shred + second Ajaw burst) is the key con.' },
  varesa: { best: [1], note: 'C1 boosts plunge damage heavily — her defining early con.' },
  chasca: { best: [1], note: 'C1 speeds up bullet loading — the biggest single upgrade to her loop.' },
  emilie: { best: [2], note: 'C1 levels cases faster; C2 (big Dendro RES shred while Burning) is her key con.' },
  chiori: { best: [1], note: 'C1 adds another doll — the most damage per pull.' },
  sigewinne: { best: [2], note: 'C1 improves bubbles; C2 adds Hydro RES shred — the key support con.' },
  nefer: { best: [1], note: 'C1 is the standout for her Lunar-Bloom reaction damage.' },
  lauma: { best: [1], note: 'C1 strengthens her Moonsign buffs for the whole team — her key support con.' },
  flins: { best: [1], note: 'Community math puts C1 as his best value-per-pull (~29% over C0), with C2 the natural stopping point. Beyond that returns fall off hard.' },
  ineffa: { best: [1], note: 'C1 improves her off-field uptime — comfortable support value.' },
  columbina: { best: [2], note: 'C1 eases her ER needs; C2 raises team Lunar reaction damage — the key con.' },
  escoffier: { best: [1], note: 'C1 extends her shred and adds damage — the strong support stop.' },
  'yae-miko': { best: [2], note: 'C1 helps energy; C2 upgrades turret range and damage — her classic breakpoint.' },
  tighnari: { best: [1], note: 'C1 adds crit rate — simple and effective.' },
  keqing: { best: [1], note: 'Cons are minor; build Aggravate first. C1 adds a little extra damage.' },
  yoimiya: { best: [1], note: 'C1 extends her Skill duration — the most practical upgrade.' },
  shenhe: { best: [1], note: 'C1 gives an extra Skill charge — community consensus is it nearly doubles her support value per rotation.' },
  nilou: { best: [1], note: 'C1 boosts her dance damage and blooms; teams matter far more than cons.' },
  baizhu: { best: [], note: 'C0 does everything his teams want (shield + Dendro). Cons are luxury.' },
  dehya: { best: [2], note: 'C2 improves her field uptime — the con that changes how she plays.' },
  albedo: { best: [2], note: 'C2 stacking transient blossoms — his best damage con.' },
  'sangonomiya-kokomi': { best: [1], note: 'C1 adds a Bake-Kurage refresh on Burst — comfort. She is complete at C0.' },
  'arataki-itto': { best: [2], note: 'C1 is nice, but C2 (party-based cooldown reduction) is his key con for mono-Geo.' },
  'yumemizuki-mizuki': { best: [1], note: 'C1 extends Dreamdrifter — more Swirl amplification uptime.' },
  durin: { best: [1], note: 'Fresh release — C1 looks like the standard early damage stop; check KQM as numbers settle.' },
  diluc: { best: [1], note: 'C1 adds damage vs full-HP enemies — modest; his weapon matters more.' },
  jean: { best: [2], note: 'C2 team movement/attack speed — the fun one. She works fully at C0.' },
  mona: { best: [], note: 'Her C1 has long-standing bug issues and none of her early cons move the needle — she is a C0 unit.' },
  qiqi: { best: [1], note: 'C1 gives energy on Skill hits — helps her worst stat (energy).' },
  klee: { best: [1], note: 'C1 adds chained mini-bombs — straightforward extra damage.' },
  venti: { best: [], note: 'C0 Venti already does his job (grouping). Cons are luxury.' },
  tartaglia: { best: [1], note: 'C1 reduces stance cooldown — the practical pick for his loop.' },
  'kamisato-ayato': { best: [1], note: 'C1 boosts Shunsuiken vs low-HP enemies — simple value.' },
  aloy: { best: [], note: 'Aloy has no constellations.' },
  dori: { best: [6], note: 'C6 adds Electro infusion and self-heal — the meme-to-real con.' },

  // ---- 4 stars: all impactful cons ----
  bennett: { best: [1, 5], note: 'C1 removes the HP condition on his ATK buff (huge). C5 lowers Burst cost. C6 adds Pyro infusion — AVOID for Physical carries, fine otherwise.' },
  xingqiu: { best: [2, 6], note: 'C2 Hydro RES shred, C6 big sword-rain damage + energy. C6 Xingqiu is a premium unit.' },
  xiangling: { best: [4], note: 'C4 extends Pyronado duration — her defining con for National teams.' },
  fischl: { best: [6], note: 'C6 makes Oz attack alongside your on-fielder — transforms her off-field damage.' },
  'kujou-sara': { best: [6], note: 'C6 adds 60% Crit DMG to Electro teammates — the reason to pull her.' },
  faruzan: { best: [6], note: 'C6 adds Crit DMG to Anemo damage — completes her as Xiao/Wanderer\'s buffer.' },
  gorou: { best: [6], note: 'C6 grants Geo Crit DMG — caps out his Itto/Noelle support role.' },
  sucrose: { best: [1], note: 'C1 second Skill charge — more Swirls, more EM sharing. She is great at C0 too.' },
  diona: { best: [6], note: 'C6 gives +200 EM to low-HP allies — notable for Hyperbloom triggers under shield.' },
  rosaria: { best: [6], note: 'C6 Physical RES shred makes her the classic Eula partner.' },
  'kuki-shinobu': { best: [4], note: 'C4 boosts her Electro damage for Hyperbloom; she mostly just needs EM.' },
  chevreuse: { best: [6], note: 'C6 team healing + more Pyro/Electro DMG — caps the Overload package.' },
  'yun-jin': { best: [6], note: 'C6 adds NA speed — great for Yoimiya and normal-attack carries.' },
  beidou: { best: [2, 6], note: 'C2 improves chain bounces; C6 shreds Electro RES during Burst.' },
  ningguang: { best: [6], note: 'C6 grants Star Jades on Burst — big charged attack follow-up.' },
  yanfei: { best: [4], note: 'C4 adds a shield on Burst — comfort for her charged-attack loop.' },
  gaming: { best: [1, 6], note: 'C1 improves his self-heal reliability; C6 adds huge plunge crit — a genuinely worthwhile C6.' },
  freminet: { best: [1], note: 'C1 crit rate on Pressure strikes — simple damage.' },
  kirara: { best: [2], note: 'C2 stronger shield — that\'s her job.' },
  charlotte: { best: [1], note: 'C1 lets her heal off-field — real utility upgrade.' },
  lynette: { best: [1], note: 'C1 extra Skill uses; support cons are all modest.' },
  kachina: { best: [2], note: 'C2 boosts Turbo Twirly damage off-field — her main damage con.' },
  ororon: { best: [2], note: 'C2 adds more Hypersense hits — straightforward off-field scaling.' },
  iansan: { best: [1], note: 'C1 raises her ATK buff cap — direct upgrade to her one job.' },
  'lan-yan': { best: [1], note: 'C1 stronger shield absorption — comfort scaling.' },
  sethos: { best: [1], note: 'C1 crit rate — clean damage for his charged shots.' },
  aino: { best: [1], note: 'C1 improves her off-field Hydro uptime for bloom teams.' },
  dahlia: { best: [1], note: 'C1 improves battery output — cheap support value.' },
  candace: { best: [6], note: 'C6 adds Hydro damage procs during her Burst — niche but fun.' },
  collei: { best: [4], note: 'C4 gives EM to the team after her Burst — helps reaction cores.' },
  yaoyao: { best: [1], note: 'C1 improves Yuegui targeting/uptime; she is a comfort pick regardless.' },
  barbara: { best: [2], note: 'C2 Hydro DMG buff + charged heal discount. C6 is the famous self-revive.' },
  xinyan: { best: [2], note: 'C2 guarantees shield level 3 — fixes her core issue.' },
  mika: { best: [6], note: 'C6 adds Physical Crit DMG — completes the Eula-support kit.' },
  thoma: { best: [6], note: 'C6 buffs NA/CA/Plunge after Burst — good for Burgeon comfort teams.' },
  sayu: { best: [1], note: 'C1 lets her roll heal + damage simultaneously — her best QoL.' },
  'shikanoin-heizou': { best: [1], note: 'C1 faster stacks — smooths his punch loop.' },
  noelle: { best: [6], note: 'C6 adds huge DEF-to-ATK conversion during Burst — her true awakening con.' },
  razor: { best: [4], note: 'C4 DEF shred on Claw and Thunder — his most universal damage con.' },
  kaeya: { best: [2], note: 'C2 extends Burst near enemies — best of a modest set.' },
  lisa: { best: [2], note: 'C2 DEF shred while holding Skill — her key interaction.' },
  amber: { best: [4], note: 'C4 second Baron Bunny — doubles her utility.' },
  chongyun: { best: [2], note: 'C2 cooldown reduction inside his field — helps every team he enables.' },
  layla: { best: [4], note: 'C4 adds NA/CA damage after shield hits — pairs with her sleepy shield job.' },
};
